### PR TITLE
Rename from Arduino_PortentaBreakoutCarrier to Arduino_PortentaBreakout

### PR DESCRIPTION
**Pull request by pennam**

### CODE REVIEW

**Review by per1234 — CHANGES_REQUESTED** [review]
A few more references to update:
- https://github.com/pennam/Arduino_PortentaBreakout/blob/rename_library/keywords.txt#L2
- https://github.com/pennam/Arduino_PortentaBreakout/blob/rename_library/README.md (L3-L5, L9)
- https://github.com/pennam/Arduino_PortentaBreakout/blob/rename_library/src/Arduino_PortentaBreakout.h#L5

**Comment by pennam** [comment]
> A few more references to update:
> 
> * https://github.com/pennam/Arduino_PortentaBreakout/blob/rename_library/keywords.txt#L2
> * https://github.com/pennam/Arduino_PortentaBreakout/blob/rename_library/README.md (L3-L5, L9)
> * https://github.com/pennam/Arduino_PortentaBreakout/blob/rename_library/src/Arduino_PortentaBreakout.h#L5

Thanks!

**Review by per1234 — APPROVED** [review]
I don't know anything about the renaming itself (though I do prefer the new name), but the changes in the PR look good to me.

**Comment by pennam** [comment]
> I don't know anything about the renaming itself (though I do prefer the new name), but the changes in the PR look good to me.

Thanks again @per1234. the renaming is due to the old one was heredited from the private repository, but this will be the official one as agreed with @facchinm

**Pull request merged**
